GET http://localhost:8080/ping
Accept: application/json

###
POST http://localhost:8080/game
Content-Type: application/json

{
  "seconds": 402,
  "routes": [
    {
      "grade": "v3",
      "finished": false
    },
    {
      "grade": "v4",
      "finished": true
    },
    {
      "grade": "v5",
      "finished": true
    },
    {
      "grade": "vB",
      "finished": true
    }
  ]
}